server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///home/alberto/personaldev/spring-microservices-in-action/configurationserver/src/main/resources/config/licensingservice
